on:
  push:
    branches:
      - '**'

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
#          PR_ID: ${{ github.event.issue.html_url }}
          PR_ID: 3
        run: |
          pwd
          ls -al
          npm i
          npm run check-labels